## Python Command Series: numpy.column_stack([[x, y] for x in xvals for y in yvals])
* I ran into this question when I was reading [A First Course in Quantitative Economics with Python
Eigenvalues and Eigenvectors](https://intro.quantecon.org/eigen_I.html)

In [6]:
import numpy as np
xvals = np.linspace(-4, 4, 9)
yvals = np.linspace(-3, 3, 7)
xygrid = np.column_stack([[x, y] for x in xvals for y in yvals])
xvals
yvals
xygrid

array([[-4., -4., -4., -4., -4., -4., -4., -3., -3., -3., -3., -3., -3.,
        -3., -2., -2., -2., -2., -2., -2., -2., -1., -1., -1., -1., -1.,
        -1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  3.,  3.,  3.,
         3.,  3.,  3.,  3.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [-3., -2., -1.,  0.,  1.,  2.,  3., -3., -2., -1.,  0.,  1.,  2.,
         3., -3., -2., -1.,  0.,  1.,  2.,  3., -3., -2., -1.,  0.,  1.,
         2.,  3., -3., -2., -1.,  0.,  1.,  2.,  3., -3., -2., -1.,  0.,
         1.,  2.,  3., -3., -2., -1.,  0.,  1.,  2.,  3., -3., -2., -1.,
         0.,  1.,  2.,  3., -3., -2., -1.,  0.,  1.,  2.,  3.]])

It is difficult to figure out how the *xggrid* is created. To figure out the mechanism behind the combination of the loops and *column_stack*, I start with simple examples.

In [2]:
import numpy as np
xvals = np.linspace(-4, -4, 1)
yvals = np.linspace(-3, 3, 7)
xygrid = np.column_stack([[x, y] for x in xvals for y in yvals])
print(f"xvals is {xvals}\n")
print(f"yvals is {yvals}\n")
print(f"xygrid is {xygrid}")

xvals is [-4.]

yvals is [-3. -2. -1.  0.  1.  2.  3.]

xygrid is [[-4. -4. -4. -4. -4. -4. -4.]
 [-3. -2. -1.  0.  1.  2.  3.]]


If *xvals* is a constant and  *yvals* is a 1 x 7 row vector, the result is a 2 x 7 matrix with the first row filled with the same constant values. Then we do the opposite.

In [4]:
import numpy as np
xvals = np.linspace(-4, 4, 9)
yvals = np.linspace(-3, -3, 1)
xygrid = np.column_stack([[x, y] for x in xvals for y in yvals])
print(f"xvals is {xvals}\n")
print(f"yvals is {yvals}\n")
print(f"xygrid is {xygrid}")

xvals is [-4. -3. -2. -1.  0.  1.  2.  3.  4.]

yvals is [-3.]

xygrid is [[-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-3. -3. -3. -3. -3. -3. -3. -3. -3.]]


Now we should have some clue aboput what's going on behind the initial codes. Let's write them in another way.

In [10]:
import numpy as np
xvals = np.linspace(-4, 4, 9)
yvals = np.linspace(-3, 3, 7)
xygrid = ("A",  "A")
for x in xvals:
    for y in yvals:
        xygrid = np.column_stack((xygrid, [x, y]))

print(f"xygrid is {xygrid}")

xygrid is [['A' '-4.0' '-4.0' '-4.0' '-4.0' '-4.0' '-4.0' '-4.0' '-3.0' '-3.0'
  '-3.0' '-3.0' '-3.0' '-3.0' '-3.0' '-2.0' '-2.0' '-2.0' '-2.0' '-2.0'
  '-2.0' '-2.0' '-1.0' '-1.0' '-1.0' '-1.0' '-1.0' '-1.0' '-1.0' '0.0'
  '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '1.0' '1.0' '1.0' '1.0' '1.0' '1.0'
  '1.0' '2.0' '2.0' '2.0' '2.0' '2.0' '2.0' '2.0' '3.0' '3.0' '3.0' '3.0'
  '3.0' '3.0' '3.0' '4.0' '4.0' '4.0' '4.0' '4.0' '4.0' '4.0']
 ['A' '-3.0' '-2.0' '-1.0' '0.0' '1.0' '2.0' '3.0' '-3.0' '-2.0' '-1.0'
  '0.0' '1.0' '2.0' '3.0' '-3.0' '-2.0' '-1.0' '0.0' '1.0' '2.0' '3.0'
  '-3.0' '-2.0' '-1.0' '0.0' '1.0' '2.0' '3.0' '-3.0' '-2.0' '-1.0' '0.0'
  '1.0' '2.0' '3.0' '-3.0' '-2.0' '-1.0' '0.0' '1.0' '2.0' '3.0' '-3.0'
  '-2.0' '-1.0' '0.0' '1.0' '2.0' '3.0' '-3.0' '-2.0' '-1.0' '0.0' '1.0'
  '2.0' '3.0' '-3.0' '-2.0' '-1.0' '0.0' '1.0' '2.0' '3.0']]
